### PR TITLE
docs: Massive overhaul of docs

### PR DESCRIPTION
**Pull request by Callisto13**
- New logos
- Matching colourscheme
- API docs
- Up to date content

Honestly I wouldn't read it all, just trust me 😉

### CODE REVIEW

**Review by yitsushi — APPROVED** [review]

**Comment by Callisto13** [comment]
can i get a quick 👍 🙏

**Comment by Skarlso** [comment]
I'm reading through it... :D

**Comment by Callisto13** [comment]
ugh dont read it loser

i didn't even read it, most of it existed before

**Comment by Skarlso** [comment]
Also Claudia:
GERGELY YOU NEVER READ.

**Comment by Callisto13** [comment]
YOU READ WHEN I TELL YOU TO READ

also ty

**Pull request merged**
