### PR TITLE
chore: updates after repo moved orgs

### PR DESCRIPTION
**Pull request by richardcase**
**What this PR does / why we need it**:

Changes after the repo was moved from the `Weaveworks` GitHub org to the
`Weaveworks-liquidmetal` GitHub org. Most of the changes are Go module
imports/definitions. There where a small numbre of lint issues after
moving and these have been fixed as well.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Checklist**:

- [x] squashed commits into logical changes

### CODE REVIEW

**Comment by yitsushi** [comment]
> yitsushi/devmapper-containerd-action@v1.0.1 is not allowed to be used in weaveworks-liquidmetal/flintlock. Actions in this workflow must be: within a repository that belongs to your Enterprise account or created by GitHub.

That's strange.

**Comment by richardcase** [comment]
> That's strange. Should we move over that repo to weaveworks?
> 
> I have no idea who can answer this, maybe @morancj ?

@yitsushi - i have updated the org settings to allow your GHA. So it should work now.

**Comment by richardcase** [comment]
Closing to kick off the GH actions again

**Comment by morancj** [comment]
Thanks Richard for [allowing specific actions](https://github.com/organizations/weaveworks-liquidmetal/settings/actions) and not just enabling all globally. :slightly_smiling_face:

**Pull request closed without merging**
