### PR TITLE
Add documentation on using OSX

### PR DESCRIPTION
**Pull request by Skarlso**
Label the PR with the kind of change this for:

kind/feature

**What this PR does / why we need it**:

Add a description on how to get started running liquid metal on OSX.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes https://github.com/weaveworks-liquidmetal/flintlock/issues/556

**Special notes for your reviewer**:

**Checklist**:

- [ ] squashed commits into logical changes
- [x] includes documentation
- [ ] adds unit tests
- [ ] adds or updates e2e tests

### CODE REVIEW

**Comment by Skarlso** [comment]
Hang on, something is missing...

**Comment by Skarlso** [comment]
Err... why doesn't add the feature label? :/

**Comment by Skarlso** [comment]
Uh, now I noticed the exitance of `extras/use-vagrant`. @Callisto13 do you think it would be better to just extend that with an OSX header?

**Comment by Callisto13** [comment]
can you add to the liquid metal docs? i am remodelling the flintlock ones

**Comment by Skarlso** [comment]
yep, no problem

**Pull request closed without merging**
